version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/auth-backend:latest
    container_name: auth-backend
    restart: always
    ports:
      - "8088:8088"
    environment:
      - PORT=8088

  frontend:
    image: ${DOCKERHUB_USERNAME}/auth-frontend:latest
    container_name: auth-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
